# Generated by Django 4.1.5 on 2023-01-13 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Baralho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('publico', models.BooleanField(default=False)),
                ('atualizado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='frente')),
                ('texto', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxima_revisao', models.DateField()),
                ('vista', models.BooleanField(default=False)),
                ('nivel', models.IntegerField(default=1)),
                ('criada', models.DateField()),
                ('baralho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas', to='baralhos.baralho')),
                ('frente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='baralhos.frente')),
                ('tags', models.ManyToManyField(to='baralhos.tag')),
                ('verso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='baralhos.verso')),
            ],
        ),
        migrations.AddField(
            model_name='baralho',
            name='tags',
            field=models.ManyToManyField(to='baralhos.tag'),
        ),
        migrations.AddField(
            model_name='baralho',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baralhos', to=settings.AUTH_USER_MODEL),
        ),
    ]
