# Generated by Django 4.1.5 on 2023-01-10 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baralhos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baralho',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baralhos', to=settings.AUTH_USER_MODEL),
        ),
    ]
